kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibmc-s3fs-default
  labels:
    app: ibmcloud-object-storage-plugin
provisioner: ibm.io/ibmc-s3fs
parameters:
  ibm.io/chunk-size-mb: "16"
  ibm.io/parallel-count: "2"
  ibm.io/multireq-max: "20"
  ibm.io/tls-cipher-suite: "AESGCM"
  ibm.io/stat-cache-size: "100000"
  ibm.io/debug-level: "warn"
  ibm.io/curl-debug: "false"
  ibm.io/kernel-cache: "false"
  ibm.io/s3fs-fuse-retry-count: "5"
  ibm.io/iam-endpoint: "https://iam.bluemix.net"
  ibm.io/object-store-endpoint: "https://dummy.default.svc.cluster.local"
  ibm.io/object-store-storage-class: "standard"
